FROM nginx:1.18-alpine

RUN rm /etc/nginx/conf.d/*.conf
COPY ./nginx.conf.template /
RUN echo "daemon off;" >> /etc/nginx/nginx.conf

COPY ./docker-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/bin/sh", "/entrypoint.sh"]
CMD [ "nginx" ]
