FROM node:12.16.3-alpine3.11

WORKDIR /usr/src/app

COPY ./package*.json /usr/src/app/

RUN npm install

COPY ./tsconfig.json /usr/src/app/

VOLUME [ "/usr/src/app/src/" ]
VOLUME [ "/usr/src/app/public/" ]

EXPOSE 80

CMD [ "npm", "start" ]