FROM node:12.16.3-alpine3.11

WORKDIR /usr/src/app

COPY ./package*.json /usr/src/app/

RUN apk add git
RUN npm install

COPY ./nodemon.json /usr/src/app/
COPY ./tsconfig.json /usr/src/app/

VOLUME [ "/usr/src/app/src/" ]

EXPOSE 3000

CMD [ "npm", "run", "dev" ]